name: Redis Service Example
on: push

jobs:
  # Label of the container job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - run: |
        docker compose up -d
        docker ps -a
    - uses: nick-fields/retry@v3
      with:
        timeout_seconds: 15
        max_attempts: 30
        continue_on_error: false
        command: |
          docker exec -i incus incus config show

    - uses: actions/github-script@v7
      with:
        script: |
          const audience = 'incus';
          const idToken = await core.getIDToken(audience);
          await io.mkdirP("~/.config/incus/oidctokens")
          await io.cp("config.yml", "~/.config/incus/config.yml")
          fs.writeFileSync("~/.config/incus/oidctokens/incus.json", JSON.stringify({
            "access_token": idToken,
            "token": "bearer",
          }))

    - run: |
        docker exec -i incus incus config set core.https_address :8443
        docker exec -i incus incus config set oidc.audience incus
        docker exec -i incus incus config set oidc.client.id incus
        docker exec -i incus incus config set oidc.issuer https://token.actions.githubusercontent.com
        curl -LO https://github.com/lxc/incus/releases/latest/download/bin.linux.incus.x86_64
        sudo install *incus* /usr/local/bin/incus
        incus list

