name: Redis Service Example
on: push

jobs:
  # Label of the container job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379
    steps:
    - uses: actions/checkout@v4
    - run: |
        docker compose up -d
        docker ps -a
        
        max_retry=50
        counter=0
        until docker exec -i incus incus config show
        do
          sleep 1
          [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
          echo "Trying again. Try #$counter"
          ((counter++))
        done

        docker exec -i incus incus config set core.https_address :8443
        curl -LO https://github.com/lxc/incus/releases/latest/download/bin.linux.incus.x86_64
        sudo install *incus* /usr/local/bin/incus

